name: SAIL CI/CD
on: 
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: pip install ".[all]"

  test:
    steps:
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - run: pip install pytest && python -m pytest --tb=native tests
