name: SAIL CI
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Branch and collaborator info
        run: |
          echo Branch Name: ${{github.ref_name}} 
          echo Triggered by: ${{github.actor}}
          echo Event: ${{github.event_name}}

      - name: Checkout sail repo
        uses: actions/checkout@v3

      - name: Install python version 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.*"
          cache: "pip"

      - name: Install Sail and its dependencies
        run: |
          pip install ".[all]"

      - name: Install scikit-multiflow
        run: pip install scikit-multiflow==0.5.3

  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Branch and collaborator info
        run: |
          echo Branch Name: ${{github.ref_name}} 
          echo Triggered by: ${{github.actor}}
          echo Event: ${{github.event_name}}

      - name: Checkout sail repo
        uses: actions/checkout@v3

      - name: Install python version 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.*"
          cache: "pip"

      - name: Install sail and its dependencies
        run: |
          pip install ".[all]"

      - name: Install scikit-multiflow
        run: pip install scikit-multiflow==0.5.3

      - name: Run unit tests with pytest
        run: pytest -s -n=auto --tb=native tests

      # - name: Run notebooks with pytest
      #   run: |
      #     pytest -s --nbmake -n=auto notebooks/*.ipynb
      #     pytest -s --nbmake -n=auto examples/*.ipynb

      # - name: Run examples with pytest
      #   run: pytest -s --script-launch-mode=subprocess -n=auto examples/*.py
